version: '3.9'
services:

  postgres_db_1:
    image: postgres
    container_name: postgres_db_1
    volumes:
      - ./postgres-data-1:/var/lib/postgresql
    env_file:
      - .env1
    networks:
      - main_network

  chat_app_1:
    build: chat_app
    container_name: chat_app_1
    entrypoint: [ "uvicorn", "chat_app.server:app", "--host", "0.0.0.0", "--port", "5000" ]
    env_file:
      - .env1
    ports:
      - 5000:5000
    networks:
      - main_network
    depends_on:
      - postgres_db_1

  postgres_db_2:
    image: postgres
    container_name: postgres_db_2
    volumes:
      - ./postgres-data-2:/var/lib/postgresql
    env_file:
      - .env2
    networks:
      - reserve_network

  chat_app_2:
    build: chat_app
    container_name: chat_app_2
    entrypoint: [ "uvicorn", "chat_app.server:app", "--host", "0.0.0.0", "--port", "5001" ]
    env_file:
      - .env2
    ports:
      - 5001:5001
    networks:
      - reserve_network
    depends_on:
      - postgres_db_2
    
  replicator:
    build: replicator
    container_name: replicator
    entrypoint: [ "python", "replicator/listener.py"]
    env_file:
      - .env
    ports:
      - 5002:5002
    networks:
      - main_network
      - reserve_network
    depends_on:
      - postgres_db_1
      - postgres_db_2

  balancer_1:
    build: balancer
    container_name: balancer_1
    entrypoint: [ "uvicorn", "balancer.server_v1:app", "--host", "0.0.0.0", "--port", "5003" ]
    env_file:
      - .env
    ports:
      - 5003:5003
    networks:
      - main_network
      - reserve_network
    depends_on:
      - postgres_db_1
      - postgres_db_2

  balancer_2:
    build: balancer
    container_name: balancer_2
    entrypoint: [ "uvicorn", "balancer.server_v2:app", "--host", "0.0.0.0", "--port", "5004" ]
    env_file:
      - .env
    ports:
      - 5004:5004
    networks:
      - main_network
      - reserve_network
    depends_on:
      - postgres_db_1
      - postgres_db_2


networks:
  main_network:
      driver: bridge
  reserve_network:
      driver: bridge