version: '3.9'
services:

  postgres_db:
    image: postgres
    container_name: postgres_db
    volumes:
      - ./postgres-data:/var/lib/postgresql
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - custom

  chat_app:
    build: chat_app
    container_name: chat_app
    env_file:
      - .env
    ports:
      - 5000:5000
    networks:
      - custom
    depends_on:
      - postgres_db

networks:
  custom:
      driver: bridge
