"""change likes

Revision ID: 118f8ed49462
Revises: 92748bb513de
Create Date: 2023-01-30 21:18:06.590345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '118f8ed49462'
down_revision = '92748bb513de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
