"""change likes

Revision ID: 92748bb513de
Revises: 0dbcf9e5c52a
Create Date: 2023-01-30 21:01:51.929593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92748bb513de'
down_revision = '0dbcf9e5c52a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
